[workspace]
resolver = "2"
members = ["*/crates/*", "2025/day01", "2025/day02", "2025/day03", "2025/day04", "crates/util", "crates/window"]

[workspace.dependencies]
util.path = "crates/util"
window.path = "crates/window"

[profile.bench]
lto = true
